import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#071527",
  },
  camera: {
    flex: 1,
  },
  capturePanel: {
    position: "absolute",
    right: 18,
    bottom: 24,
    left: 18,
  },
  captureBar: {
    gap: 10,
    borderWidth: 2,
    borderColor: "#F8F0DC",
    borderRadius: 16,
    padding: 14,
    backgroundColor: "rgba(9, 42, 76, 0.94)",
  },
  captureTitle: {
    color: "#F8F0DC",
    fontSize: 18,
    fontWeight: "900",
    textAlign: "center",
  },
  captureHint: {
    color: "#F8F0DC",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  captureError: {
    borderWidth: 2,
    borderColor: "#F8F0DC",
    borderRadius: 12,
    padding: 10,
    backgroundColor: "#E66A2C",
    color: "#F8F0DC",
    fontSize: 14,
    fontWeight: "800",
    textAlign: "center",
  },
  reviewPanel: {
    position: "absolute",
    top: 42,
    right: 14,
    bottom: 20,
    left: 14,
    borderWidth: 2,
    borderColor: "#F8F0DC",
    borderRadius: 18,
    backgroundColor: "rgba(8, 30, 52, 0.97)",
    overflow: "hidden",
  },
  reviewLayout: {
    flex: 1,
  },
  reviewScroll: {
    flex: 1,
  },
  reviewContent: {
    gap: 12,
    padding: 12,
  },
  reviewFooter: {
    borderTopWidth: 2,
    borderTopColor: "rgba(248, 240, 220, 0.35)",
    padding: 12,
    paddingTop: 10,
    backgroundColor: "rgba(8, 30, 52, 0.98)",
  },
  newScanButton: {
    width: "100%",
    paddingVertical: 9,
    paddingHorizontal: 10,
  },
  checkingPanel: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    borderWidth: 2,
    borderColor: "#F2B84B",
    borderRadius: 14,
    padding: 10,
    backgroundColor: "#092A4C",
  },
  checkingText: {
    flex: 1,
    color: "#F8F0DC",
    fontSize: 13,
    fontWeight: "900",
  },
  candidatePanel: {
    gap: 10,
    borderWidth: 2,
    borderColor: "#F2B84B",
    borderRadius: 14,
    padding: 10,
    backgroundColor: "#123F6D",
  },
  candidateSummary: {
    flexDirection: "row",
    gap: 12,
  },
  cardImage: {
    width: 126,
    aspectRatio: 0.716,
    borderWidth: 2,
    borderColor: "#F8F0DC",
    borderRadius: 10,
    backgroundColor: "#071527",
  },
  imagePlaceholder: {
    alignItems: "center",
    justifyContent: "center",
    width: 126,
    aspectRatio: 0.716,
    borderWidth: 2,
    borderColor: "#F8F0DC",
    borderRadius: 10,
    backgroundColor: "#071527",
  },
  imagePlaceholderText: {
    color: "#F8F0DC",
    fontSize: 12,
    fontWeight: "900",
  },
  candidateInfo: {
    flex: 1,
    justifyContent: "space-between",
  },
  candidateInfoTop: {
    gap: 8,
  },
  candidateName: {
    color: "#F8F0DC",
    fontSize: 19,
    fontWeight: "900",
  },
  candidateMeta: {
    color: "#F2B84B",
    fontSize: 15,
    fontWeight: "900",
  },
  confidenceBadge: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  searchBadge: {
    backgroundColor: "#E66A2C",
  },
  confidenceText: {
    color: "#F8F0DC",
    fontSize: 12,
    fontWeight: "900",
  },
  priceBlock: {
    alignSelf: "stretch",
    gap: 6,
    marginTop: 2,
  },
  priceMetricRow: {
    flexDirection: "row",
    gap: 8,
  },
  priceMetric: {
    flex: 1,
    borderWidth: 1,
    borderColor: "rgba(248, 240, 220, 0.65)",
    borderRadius: 10,
    paddingVertical: 7,
    paddingHorizontal: 6,
    backgroundColor: "rgba(7, 21, 39, 0.36)",
  },
  priceMetricLabel: {
    color: "#F2B84B",
    fontSize: 9,
    fontWeight: "900",
    textAlign: "center",
    textTransform: "uppercase",
  },
  priceMetricValue: {
    color: "#F8F0DC",
    fontSize: 13,
    fontWeight: "900",
    textAlign: "center",
  },
  priceStatusText: {
    color: "#F8F0DC",
    fontSize: 13,
    fontWeight: "800",
    textAlign: "center",
  },
  cardPriceButton: {
    alignSelf: "stretch",
    paddingVertical: 10,
  },
  editDropdownPanel: {
    gap: 10,
    borderWidth: 2,
    borderColor: "#F8F0DC",
    borderRadius: 14,
    padding: 10,
    backgroundColor: "#092A4C",
  },
  editToggle: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  editToggleText: {
    color: "#F8F0DC",
    fontSize: 13,
    fontWeight: "900",
  },
  editToggleIcon: {
    minWidth: 26,
    color: "#F2B84B",
    fontSize: 22,
    fontWeight: "900",
    lineHeight: 24,
    textAlign: "center",
  },
  inlineEditPanel: {
    gap: 9,
  },
  candidateStrip: {
    gap: 7,
    borderWidth: 2,
    borderColor: "#F8F0DC",
    borderRadius: 14,
    padding: 8,
    backgroundColor: "#092A4C",
  },
  candidateStripHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  candidateStripTitle: {
    color: "#F2B84B",
    fontSize: 13,
    fontWeight: "900",
  },
  candidateStripHint: {
    color: "#F8F0DC",
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
  },
  candidateStripList: {
    gap: 10,
    paddingRight: 2,
  },
  candidateTile: {
    width: 84,
    gap: 4,
    borderWidth: 2,
    borderColor: "#F8F0DC",
    borderRadius: 12,
    padding: 6,
    backgroundColor: "#123F6D",
  },
  candidateTileImage: {
    width: "100%",
    aspectRatio: 0.716,
    borderRadius: 8,
    backgroundColor: "#071527",
  },
  candidateTileImagePlaceholder: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    aspectRatio: 0.716,
    borderRadius: 8,
    backgroundColor: "#071527",
  },
  candidateTileName: {
    color: "#F8F0DC",
    fontSize: 10,
    fontWeight: "900",
    textAlign: "center",
  },
  candidateTileMeta: {
    color: "#F2B84B",
    fontSize: 10,
    fontWeight: "900",
    textAlign: "center",
  },
  statusMessage: {
    borderWidth: 2,
    borderColor: "#F8F0DC",
    borderRadius: 12,
    padding: 10,
    backgroundColor: "#0B355F",
    color: "#F8F0DC",
    fontSize: 13,
    fontWeight: "800",
    textAlign: "center",
  },
  collectionPanel: {
    gap: 10,
    borderWidth: 2,
    borderColor: "#F8F0DC",
    borderRadius: 14,
    padding: 10,
    backgroundColor: "#092A4C",
  },
  collectionOptions: {
    flexDirection: "row",
    gap: 10,
  },
  quantityControl: {
    flex: 1,
    gap: 8,
  },
  printingControl: {
    flex: 1.35,
    gap: 8,
  },
  optionLabel: {
    color: "#F8F0DC",
    fontSize: 12,
    fontWeight: "900",
    textAlign: "center",
  },
  stepperRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
  },
  stepperButton: {
    minWidth: 42,
    paddingVertical: 7,
    paddingHorizontal: 8,
  },
  quantityValue: {
    minWidth: 30,
    color: "#F8F0DC",
    fontSize: 20,
    fontWeight: "900",
    textAlign: "center",
  },
  segmentedControl: {
    flexDirection: "row",
    borderWidth: 2,
    borderColor: "#F8F0DC",
    borderRadius: 12,
    overflow: "hidden",
  },
  segmentButton: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 10,
    backgroundColor: "#123F6D",
  },
  segmentButtonActive: {
    backgroundColor: "#F2B84B",
  },
  segmentButtonDisabled: {
    opacity: 0.55,
  },
  segmentText: {
    color: "#F8F0DC",
    fontSize: 12,
    fontWeight: "900",
  },
  segmentTextActive: {
    color: "#071527",
  },
  collectionMessage: {
    color: "#F8F0DC",
    fontSize: 12,
    fontWeight: "800",
    textAlign: "center",
  },
  row: {
    flexDirection: "row",
    gap: 10,
  },
  input: {
    borderWidth: 2,
    borderColor: "#F2B84B",
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: "#F8F0DC",
    color: "#071527",
    fontSize: 16,
    fontWeight: "800",
  },
  compactInput: {
    flex: 1,
  },
  actionButton: {
    flex: 1,
  },
  centered: {
    flex: 1,
    gap: 18,
    justifyContent: "center",
    padding: 24,
    backgroundColor: "#071527",
  },
  message: {
    color: "#F8F0DC",
    fontSize: 22,
    fontWeight: "900",
    textAlign: "center",
  },
});
