import { RiftboundCard } from './cards.types';

export const cards: RiftboundCard[] = [
  {
    id: 'ogn-jinx-loose-cannon',
    name: 'Jinx, Loose Cannon',
    set: 'Origins',
    setCode: 'OGN',
    number: '004',
    color: 'Red',
    cost: 4,
    type: 'Champion',
    cardmarketPath: '/en/Riftbound/Cards/Jinx-Loose-Cannon',
  },
  {
    id: 'ogn-jinx-rebel',
    name: 'Jinx, Rebel',
    set: 'Origins',
    setCode: 'OGN',
    number: '143',
    color: 'Red',
    cost: 4,
    type: 'Unit',
    cardmarketPath: '/en/Riftbound/Cards/Jinx-Rebel',
  },
  {
    id: 'ogn-teemo-scout',
    name: 'Teemo, Scout',
    set: 'Origins',
    setCode: 'OGN',
    number: '021',
    color: 'Green',
    cost: 2,
    type: 'Champion',
    cardmarketPath: '/en/Riftbound/Cards/Teemo-Scout',
  },
  {
    id: 'ogn-lux-crownguard',
    name: 'Lux, Crownguard',
    set: 'Origins',
    setCode: 'OGN',
    number: '072',
    color: 'White',
    cost: 3,
    type: 'Unit',
    cardmarketPath: '/en/Riftbound/Cards/Lux-Crownguard',
  },
  {
    id: 'ogn-miss-fortune-bounty-hunter',
    name: 'Miss Fortune, Bounty Hunter',
    set: 'Origins',
    setCode: 'OGN',
    number: '088',
    color: 'Red',
    cost: 4,
    type: 'Champion',
    cardmarketPath: '/en/Riftbound/Cards/Miss-Fortune-Bounty-Hunter',
  },
  {
    id: 'ogn-yasuo-unforgiven',
    name: 'Yasuo, Unforgiven',
    set: 'Origins',
    setCode: 'OGN',
    number: '111',
    color: 'Blue',
    cost: 5,
    type: 'Champion',
  },
  {
    id: 'ogn-ahri-nine-tailed-fox',
    name: 'Ahri, Nine-Tailed Fox',
    set: 'Origins',
    setCode: 'OGN',
    number: '019',
    color: 'Blue',
    cost: 3,
    type: 'Champion',
    cardmarketPath: '/en/Riftbound/Cards/Ahri-Nine-Tailed-Fox',
  },
  {
    id: 'ogn-garen-might-of-demacia',
    name: 'Garen, Might of Demacia',
    set: 'Origins',
    setCode: 'OGN',
    number: '061',
    color: 'White',
    cost: 5,
    type: 'Champion',
    cardmarketPath: '/en/Riftbound/Cards/Garen-Might-of-Demacia',
  },
  {
    id: 'ogn-lee-sin-blind-monk',
    name: 'Lee Sin, Blind Monk',
    set: 'Origins',
    setCode: 'OGN',
    number: '104',
    color: 'Green',
    cost: 4,
    type: 'Champion',
    cardmarketPath: '/en/Riftbound/Cards/Lee-Sin-Blind-Monk',
  },
  {
    id: 'ogn-darius-hand-of-noxus',
    name: 'Darius, Hand of Noxus',
    set: 'Origins',
    setCode: 'OGN',
    number: '051',
    color: 'Red',
    cost: 5,
    type: 'Champion',
    cardmarketPath: '/en/Riftbound/Cards/Darius-Hand-of-Noxus',
  },
  {
    id: 'ogn-zed-master-of-shadows',
    name: 'Zed, Master of Shadows',
    set: 'Origins',
    setCode: 'OGN',
    number: '127',
    color: 'Black',
    cost: 4,
    type: 'Champion',
  },
  {
    id: 'ogn-kai-sa-daughter-of-the-void',
    name: "Kai'Sa, Daughter of the Void",
    set: 'Origins',
    setCode: 'OGN',
    number: '096',
    color: 'Purple',
    cost: 3,
    type: 'Champion',
    cardmarketPath: '/en/Riftbound/Cards/Kaisa-Daughter-of-the-Void',
  },
  {
    id: 'ogn-annie-dark-child',
    name: 'Annie, Dark Child',
    set: 'Origins',
    setCode: 'OGN',
    number: '032',
    color: 'Red',
    cost: 2,
    type: 'Champion',
    cardmarketPath: '/en/Riftbound/Cards/Annie-Dark-Child',
  },
  {
    id: 'ogn-flash',
    name: 'Flash',
    set: 'Origins',
    setCode: 'OGN',
    number: '188',
    color: 'Yellow',
    cost: 1,
    type: 'Spell',
    cardmarketPath: '/en/Riftbound/Cards/Flash',
  },
  {
    id: 'ogn-hidden-blade',
    name: 'Hidden Blade',
    set: 'Origins',
    setCode: 'OGN',
    number: '214',
    color: 'Black',
    cost: 2,
    type: 'Spell',
    cardmarketPath: '/en/Riftbound/Cards/Hidden-Blade',
  },
  {
    id: 'ogn-defy',
    name: 'Defy',
    set: 'Origins',
    setCode: 'OGN',
    number: '173',
    color: 'White',
    cost: 1,
    type: 'Spell',
    cardmarketPath: '/en/Riftbound/Cards/Defy',
  },
  {
    id: 'sfd-guardian-angel',
    name: 'Guardian Angel',
    set: 'Spiritforged',
    setCode: 'SFD',
    number: '045',
    color: 'White',
    cost: 3,
    type: 'Gear',
    cardmarketPath: '/en/Riftbound/Cards/Guardian-Angel',
  },
  {
    id: 'sfd-rek-sai-breacher',
    name: "Rek'Sai, Breacher",
    set: 'Spiritforged',
    setCode: 'SFD',
    number: '092',
    color: 'Purple',
    cost: 5,
    type: 'Champion',
  },
  {
    id: 'sfd-arise',
    name: 'Arise!',
    set: 'Spiritforged',
    setCode: 'SFD',
    number: '159',
    color: 'White',
    cost: 2,
    type: 'Spell',
    cardmarketPath: '/en/Riftbound/Cards/Arise',
  },
  {
    id: 'unl-baron-nashor',
    name: 'Baron Nashor',
    set: 'Unleashed',
    setCode: 'UNL',
    number: '001',
    color: 'Purple',
    cost: 8,
    type: 'Unit',
    cardmarketPath: '/en/Riftbound/Cards/Baron-Nashor',
  },
];
