import { CardmarketOverride } from './cardmarket.types';

export const cardmarketOverrides: CardmarketOverride[] = [
  {
    riftboundId: 'ogn-243',
    setCode: 'OGN',
    number: '243',
    name: 'Darius, Executioner',
    type: 'Champion',
    rarity: 'Epic',
    cardmarketPath: '/en/Riftbound/Products/Singles/Origins/Darius-Executioner-V1-Epic',
    notes: 'Manual seed',
  },
  {
    riftboundId: 'ogn-243a',
    setCode: 'OGN',
    number: '243A',
    name: 'Darius, Executioner',
    type: 'Champion',
    rarity: 'Epic',
    cardmarketPath: '/en/Riftbound/Products/Singles/Origins/Darius-Executioner-V2-Overnumbered',
    notes: 'Manual seed',
  },
  {
    riftboundId: 'sfd-236',
    setCode: 'SFD',
    number: '236',
    name: 'Darius, Executioner',
    type: 'Champion',
    rarity: 'Showcase',
    cardmarketPath: '/en/Riftbound/Products/Singles/Spiritforged/Darius-Executioner-V1-Showcase',
    notes: 'Manual seed',
  },
  {
    riftboundId: 'sfd-236*',
    setCode: 'SFD',
    number: '236*',
    name: 'Darius, Executioner',
    type: 'Champion',
    rarity: 'Showcase',
    cardmarketPath: '/en/Riftbound/Products/Singles/Spiritforged/Darius-Executioner-V2-Signed-Showcase',
    notes: 'Manual seed',
  },
  {
    setCode: 'OGN',
    number: '308',
    name: 'Viktor, Herald of the Arcane',
    type: 'Legend',
    cardmarketPath: '/en/Riftbound/Products/Singles/Origins/Viktor-Herald-of-the-Arcane',
    notes: 'Manual seed',
  },
  {
    setCode: 'OGN',
    number: '308A',
    name: 'Viktor, Herald of the Arcane',
    type: 'Legend',
    cardmarketPath: '/en/Riftbound/Products/Singles/Origins/Viktor-Herald-of-the-Arcane-V2-Overnumbered',
    notes: 'Manual seed',
  },
  {
    setCode: 'OGN',
    number: '308*',
    name: 'Viktor, Herald of the Arcane',
    type: 'Legend',
    cardmarketPath: '/en/Riftbound/Products/Singles/Origins/Viktor-Herald-of-the-Arcane-V3-Overnumbered',
    notes: 'Manual seed',
  },
  {
    setCode: 'SFD',
    number: '119',
    name: 'Jax, Unrelenting',
    type: 'Champion',
    rarity: 'Epic',
    cardmarketPath: '/en/Riftbound/Products/Singles/Spiritforged/Jax-Unrelenting-V1-Epic',
    notes: 'Manual correction',
  },
  {
    setCode: 'SFD',
    number: '119A',
    name: 'Jax, Unrelenting',
    type: 'Champion',
    rarity: 'Showcase',
    cardmarketPath: '/en/Riftbound/Products/Singles/Spiritforged/Jax-Unrelenting-V2-Showcase',
    notes: 'Manual correction',
  },
];
